iCub::boostMIL::MILClassifier Class Reference
MIL Classifier A weak classifier implementing the Multiple Instance Learning in an online boosting framework.
#include <MILClassifier.h>
Public Member Functions
MILClassifier (const std::string &_type, yarp::os::ResourceFinder &_resource, const double *_center=NULL)
MILClassifier (const MILClassifier &mil, const double *_center=NULL)
virtual void clear ()
Clear Method.
virtual bool isReady ()
Updates the classifier and verifies if it is ready to be trained and to classify.
virtual std::string toString () const
Encodes the classifier in a single string.
virtual void fromString (const std::string &str)
Loads a classifier from a string.
virtual void toStream (std::ofstream &fout) const
Encodes the classifier in a single string.
virtual void fromStream (std::ifstream &fin)
Loads a classifier from a string.
virtual int classify (const Inputs *input, Output *output) const
Classifies the given input.
virtual void update (const Inputs *input, double &weight)
Updates the classifier with respect to an input with associated weight.
virtual double error_rate (const std::list< const Inputs * > &dataset, std::list< double > &weights)
virtual std::list< WeakClassifier * > * pack (const Inputs *input) const
Extract the input information relative to this classifier type and creates a list of WeakClassifiers from it.
virtual MILClassifier * create () const
Virtual Constructor.
std::string getType () const
Returns the classifier type information.
double getError () const
Returns the current error exhibited by the classifier.
virtual double error_rate (const std::list< Inputs * > &dataset)
Returns the error rate of the classifier over a given dataset assuming uniform weight distribution.
virtual double error_rate (const std::list< Inputs * > &dataset, const std::list< double > &weights)
Returns the error rate of the classifier over a given dataset with specified weight distribution.
virtual double margin (const Inputs *input, Output *output=NULL) const
Margin, in general it is the same as classify.
Protected Member Functions
virtual void initResource ()
virtual double distanceFromCenter (const double *vec) const
virtual void setCenter (const double *_center)
void insertBag (const double &dist, const int &label, const double &weight)
double bestRadius ()
Protected Attributes
int feature_size
yarp::sig::Vector center
double radius
std::deque< Bag > cache
int max_cache_size
double posweight
double negweight
yarp::os::ResourceFinder & resource
Resource containing the parameters information.
std::string type
The type associated to the WeakClassifier.
double error
Last computed error.
bool ready
Checks if the WeakClassifier has been initialized.
bool verbose
Allows prints by the boostMIL library.
Detailed Description
MIL Classifier A weak classifier implementing the Multiple Instance Learning in an online boosting framework.
Definition at line 96 of file MILClassifier.h.
Member Function Documentation
int MILClassifier::classify (const Inputs * input, Output * output) const [virtual]
Classifies the given input.
Parameters
input the input to classify.
Returns
1,-1 or 0 if the classifier classifies the input (respectively): positive, negative or undetermined (e.g. the classifier is not ready to classify yet).
Implements iCub::boostMIL::WeakClassifier.
Definition at line 297 of file MILClassifier.cpp.
References iCub::boostMIL::WeakClassifier::ready, and iCub::boostMIL::WeakClassifier::type.
{
    if(!ready)
        return 0;
    const yarp::sig::Vector *bag = input->getInput(type);
    if(!bag)
        return 0;
    if(radius<0)
        return +1;
    if(bag->size() % feature_size != 0 || feature_size == 0)
    {
        std::ostringstream buffer;
        buffer << "MILClassifier of type: '" << type << "'" << std::endl;
        buffer << "Wrong input size: " << bag->size() << " is not divisible by " << feature_size;
        throw std::runtime_error(buffer.str());
    }
    int label=-1;
    for(size_t i = 0; i < bag->size(); i += feature_size)
    {
        //compute the distance between the two vectors
        double dist=distanceFromCenter(bag->data()+i);
        if(dist<radius)
        {
            label=+1;
                
            yarp::sig::Vector p=input->getPosition(type,i/feature_size);
            if(output!=NULL)
                output->pushPosition(input->getPosition(type,i/feature_size));
        }
    }
    return label;
}
void MILClassifier::clear () [virtual]
Clear Method.
Returns the classifier to its original condition (Pre-initialization).
Implements iCub::boostMIL::WeakClassifier.
Definition at line 273 of file MILClassifier.cpp.
References iCub::boostMIL::WeakClassifier::ready.
Referenced by fromStream(), and fromString().
{
    ready=false;
    radius = 0;
    feature_size = 0;
    max_cache_size = 0;
    posweight = 0.0;
    negweight = 0.0;
    cache.clear();
    center.zero();
    center.clear();
}
virtual double iCub::boostMIL::WeakClassifier::error_rate (const std::list< Inputs * > & dataset) [inline], [virtual], [inherited]
Returns the error rate of the classifier over a given dataset assuming uniform weight distribution.
Parameters
dataset the datataset over which compute the error rate.
Returns
the error rate.
Definition at line 158 of file WeakClassifier.h.
    {
        std::list<double> weights(dataset.size(),1.0/dataset.size());
        return error_rate(dataset,weights);
    }
virtual double iCub::boostMIL::WeakClassifier::error_rate (const std::list< Inputs * > & dataset, const std::list< double > & weights) [inline], [virtual], [inherited]
Returns the error rate of the classifier over a given dataset with specified weight distribution.
Parameters
dataset the datataset over which compute the error rate.
weights the weight distribution over the given dataset.
Returns
the error rate.
Definition at line 171 of file WeakClassifier.h.
References iCub::boostMIL::WeakClassifier::classify().
    {
        double e = 0.0;
        std::list<Inputs*> ::const_iterator d_itr = dataset.begin();
        std::list<double> ::const_iterator w_itr = weights.begin();
        while(d_itr != dataset.begin())
        {
            if(classify(*d_itr) != (*d_itr)->getLabel())
                e += *w_itr;
            d_itr++;
        }
        return e;
    }
void MILClassifier::fromStream (std::ifstream & fin) [virtual]
Loads a classifier from a string.
Parameters
the string encoding the classifier to be loaded
Implements iCub::boostMIL::WeakClassifier.
Definition at line 361 of file MILClassifier.cpp.
References clear(), and isReady().
{
    clear();
    fin.read((char*)&feature_size,sizeof(int));
    fin.read((char*)&radius,sizeof(double));
    fin.read((char*)&posweight,sizeof(double));
    fin.read((char*)&negweight,sizeof(double));
    center.resize(feature_size);
    for(int i=0; i<feature_size; i++)
        fin.read((char*)&center[i],sizeof(double));
    int cache_size;
    fin.read((char*)&cache_size,sizeof(int));
    cache.resize(cache_size);
    for(int i=0; i<cache_size; i++)
        fin.read((char*)&cache[i],sizeof(Bag));
    isReady();
}
void MILClassifier::fromString (const std::string & str) [virtual]
Loads a classifier from a string.
Parameters
the string encoding the classifier to be loaded
Implements iCub::boostMIL::WeakClassifier.
Definition at line 414 of file MILClassifier.cpp.
References clear(), isReady(), and iCub::boostMIL::WeakClassifier::type.
{
    clear();
    yarp::os::Bottle bLoader(str.c_str());
    type=bLoader.find("type").asString().c_str();
    feature_size=bLoader.find("feature_size").asInt();
    radius=bLoader.find("radius").asDouble();
    posweight=bLoader.find("posweight").asDouble();
    negweight=bLoader.find("negweight").asDouble();
    yarp::os::Bottle *bCenter=bLoader.find("center").asList();
    for(int i=0; i<bCenter->size(); i++)
        center.push_back(bCenter->get(i).asDouble());
    yarp::os::Bottle *bCache=bLoader.find("cache").asList();
    for(int i=0; i<bCache->size(); i++)
    {
        Bag b;
        b.fromString(bCache->get(i).asList()->toString().c_str());
        cache.push_back(b);
    }
    isReady();
}
double iCub::boostMIL::WeakClassifier::getError () const [inline], [inherited]
Returns the current error exhibited by the classifier.
Returns
the current error.
Definition at line 140 of file WeakClassifier.h.
References iCub::boostMIL::WeakClassifier::error.
Referenced by iCub::boostMIL::AdaBoost::train(), and iCub::boostMIL::OnlineBoost::update().
{return error;}
std::string iCub::boostMIL::WeakClassifier::getType () const [inline], [inherited]
Returns the classifier type information.
Returns
the type of the classifier
Definition at line 133 of file WeakClassifier.h.
References iCub::boostMIL::WeakClassifier::type.
Referenced by iCub::boostMIL::ClassifierFactory::registerClassifier(), iCub::boostMIL::SelectorClassifier::toStream(), iCub::boostMIL::OnlineBoost::toStream(), iCub::boostMIL::OnlineSupport::toStream(), iCub::boostMIL::AvgClassifier::toStream(), and iCub::boostMIL::StrongClassifier::toStream().
{return type;}
bool MILClassifier::isReady () [virtual]
Updates the classifier and verifies if it is ready to be trained and to classify.
Returns
true if and only if the classifier is ready.
Implements iCub::boostMIL::WeakClassifier.
Definition at line 290 of file MILClassifier.cpp.
References iCub::boostMIL::WeakClassifier::ready.
Referenced by fromStream(), and fromString().
{
    ready = (feature_size != 0 && feature_size == center.size());
    return ready;
}
virtual double iCub::boostMIL::WeakClassifier::margin (const Inputs * input, Output * output = NULL) const [inline], [virtual], [inherited]
Margin, in general it is the same as classify.
Parameters
input the input to classify.
Returns
1,-1 or 0 if the classifier classifies the input (respectively): positive, negative or undetermined (e.g. the classifier is not ready to classify yet).
Reimplemented in iCub::boostMIL::OnlineSupport, iCub::boostMIL::AvgClassifier, and iCub::boostMIL::StrongClassifier.
Definition at line 249 of file WeakClassifier.h.
References iCub::boostMIL::WeakClassifier::classify().
    {
        return classify(input,output);
    }
std::list< WeakClassifier * > * MILClassifier::pack (const Inputs * input) const [virtual]
Extract the input information relative to this classifier type and creates a list of WeakClassifiers from it.
Used for online methods to create the space of hypothesys directly from training data. Usually returns a null pointer.
Parameters
input the input from which extract the WeakClassifiers.
Returns
a list of pointers to the WeakClassifiers extracted from the input.
Reimplemented from iCub::boostMIL::WeakClassifier.
Definition at line 531 of file MILClassifier.cpp.
References iCub::boostMIL::WeakClassifier::resource, and iCub::boostMIL::WeakClassifier::type.
{
    std::list<WeakClassifier*> *list = NULL;
    if(input!=NULL)
    {
        list=new std::list<WeakClassifier*>;
        const yarp::sig::Vector *bag = input->getInput(type);
        //if the Correesponding input is found, pack it
        if(bag)
        {
            //check that the vector dimension is divisible by the feature_size
            if(bag->size()%feature_size != 0 || feature_size == 0)
            {
                std::ostringstream buffer;
                buffer << "MILClassifier of type: '" << type << "'" << std::endl;
                buffer << "Wrong input size: " << bag->size() << " is not divisible by " << feature_size;
                throw std::runtime_error(buffer.str());
            }
            for(size_t i= 0; i < bag->size(); i += feature_size)
                list->push_back(new MILClassifier(type,resource,bag->data()+i));
        }
    }
    return list;
}
void MILClassifier::toStream (std::ofstream & fout) const [virtual]
Encodes the classifier in a single string.
Implements iCub::boostMIL::WeakClassifier.
Definition at line 342 of file MILClassifier.cpp.
{
    fout.write((char*)&feature_size,sizeof(int));
    fout.write((char*)&radius,sizeof(double));
    fout.write((char*)&posweight,sizeof(double));
    fout.write((char*)&negweight,sizeof(double));
    for(int i=0; i<feature_size; i++)
        fout.write((char*)&center[i],sizeof(double));
    int cache_size=cache.size();
    fout.write((char*)&cache_size,sizeof(int));
    for(int i=0; i<cache_size; i++)
        fout.write((char*)&cache[i],sizeof(Bag));
}
std::string MILClassifier::toString () const [virtual]
Encodes the classifier in a single string.
Returns
a string encoding the current classifier form
Implements iCub::boostMIL::WeakClassifier.
Definition at line 389 of file MILClassifier.cpp.
References iCub::boostMIL::WeakClassifier::type.
{
    std::stringstream strstr;
    strstr << "(type " << type << ") ";
    strstr << "(feature_size " << feature_size << ") ";
    strstr << "(radius " << radius << ") ";
    strstr << "(posweight " << posweight << ") ";
    strstr << "(negweight " << negweight << ") ";
    strstr << "(center (";
    for(size_t i=0; i<center.size(); i++)
        strstr << center[i] << " ";
    strstr << ")) ";
    strstr << "(cache (";
    for(unsigned int i=0; i<cache.size(); i++)
        strstr << "(" << cache[i].toString() << ") ";
    strstr << ")) ";
    return strstr.str().c_str();
}
void MILClassifier::update (const Inputs * input, double & weight) [virtual]
Updates the classifier with respect to an input with associated weight.
Usually an online method.
Parameters
input the input.
the relevance weight associated to the given input.
Implements iCub::boostMIL::WeakClassifier.
Definition at line 445 of file MILClassifier.cpp.
References iCub::boostMIL::WeakClassifier::type.
{
    const yarp::sig::Vector *bag = input->getInput(type);
    if(bag)
    {
        //check that the vector dimension is divisible by the feature_size
        if(bag->size()%feature_size != 0 || feature_size == 0)
        {
            std::ostringstream buffer;
            buffer << "MILClassifier of type: '" << type << "'" << std::endl;
            buffer << "Wrong input size: " << bag->size() << " is not divisible by " << feature_size;
            throw std::runtime_error(buffer.str());
        }
        //find the element in the bag which is nearest to the weak classifier center
        double min_dist = -1.0;
        for(size_t i = 0; i < bag->size(); i+=feature_size)
        {
            double dist = distanceFromCenter(bag->data()+i);
            if(dist < min_dist || min_dist < 0.0)
                min_dist = dist;
        }
        //insert the element in the right position of the cache
        insertBag(min_dist,input->getLabel(),weight);
        //find the best radius and update the error
        radius = bestRadius();
    }
}
The documentation for this class was generated from the following files:
C:/dev/icub-contrib-iit/boost-mil/lib/include/iCub/boostMIL/MILClassifier.h
C:/dev/icub-contrib-iit/boost-mil/lib/src/MILClassifier.cpp