iCub::boostMIL::AvgClassifier Class Reference
Avg Classifier.
#include <AvgClassifier.h>
Public Member Functions
AvgClassifier (const int &_type, yarp::os::ResourceFinder &_resource, std::deque< WeakClassifier * > *_function_space)
AvgClassifier (const std::string &_type, yarp::os::ResourceFinder &_resource, std::deque< WeakClassifier * > *_function_space)
virtual bool isReady ()
Updates the classifier and verifies if it is ready to be trained and to classify.
virtual void clear ()
Clear Method.
virtual std::string toString () const
Encodes the classifier in a single string.
virtual void fromStream (std::ifstream &fin)
Loads a classifier from a string.
virtual void toStream (std::ofstream &fout) const
Encodes the classifier in a single string.
virtual void fromString (const std::string &str)
Loads a classifier from a string.
virtual int classify (const Inputs *input, Output *output) const
Classifies the given input.
virtual double margin (const Inputs *input, Output *output) const
Margin given the input.
virtual void update (const Inputs *input, double &weight)
Updates the classifier with respect to an input with associated weight.
std::string getType () const
Returns the classifier type information.
double getError () const
Returns the current error exhibited by the classifier.
virtual double error_rate (const std::list< Inputs * > &dataset)
Returns the error rate of the classifier over a given dataset assuming uniform weight distribution.
virtual double error_rate (const std::list< Inputs * > &dataset, const std::list< double > &weights)
Returns the error rate of the classifier over a given dataset with specified weight distribution.
Protected Attributes
yarp::os::ResourceFinder & resource
Resource containing the parameters information.
std::string type
The type associated to the WeakClassifier.
double error
Last computed error.
bool ready
Checks if the WeakClassifier has been initialized.
bool verbose
Allows prints by the boostMIL library.
Detailed Description
Avg Classifier.
Definition at line 93 of file AvgClassifier.h.
Member Function Documentation
int AvgClassifier::classify (const Inputs * input, Output * output) const [virtual]
Classifies the given input.
Parameters
input the input to classify.
Returns
1,-1 or 0 if the classifier classifies the input (respectively): positive, negative or undetermined (e.g. the classifier is not ready to classify yet).
Implements iCub::boostMIL::WeakClassifier.
Definition at line 141 of file AvgClassifier.cpp.
References margin().
{
    if(this->margin(input,output)>threshold)
        return 1;
    else
        return -1;
}
void AvgClassifier::clear () [virtual]
Clear Method.
Returns the classifier to its original condition (Pre-initialization).
Implements iCub::boostMIL::WeakClassifier.
Definition at line 101 of file AvgClassifier.cpp.
References iCub::boostMIL::WeakClassifier::ready.
Referenced by fromStream(), and fromString().
{
    ready=false;
    if(!threshold_fixed)
        threshold=1.0;
    posweight = 0.0;
    negweight = 0.0;
    pool_size = 0;
    while(pool.size())
    {
        delete pool.back();
        pool.pop_back();
    }
    correct.clear();
    wrong.clear();
    alpha.clear();
}
virtual double iCub::boostMIL::WeakClassifier::error_rate (const std::list< Inputs * > & dataset) [inline], [virtual], [inherited]
Returns the error rate of the classifier over a given dataset assuming uniform weight distribution.
Parameters
dataset the datataset over which compute the error rate.
Returns
the error rate.
Definition at line 158 of file WeakClassifier.h.
    {
        std::list<double> weights(dataset.size(),1.0/dataset.size());
        return error_rate(dataset,weights);
    }
virtual double iCub::boostMIL::WeakClassifier::error_rate (const std::list< Inputs * > & dataset, const std::list< double > & weights) [inline], [virtual], [inherited]
Returns the error rate of the classifier over a given dataset with specified weight distribution.
Parameters
dataset the datataset over which compute the error rate.
weights the weight distribution over the given dataset.
Returns
the error rate.
Definition at line 171 of file WeakClassifier.h.
References iCub::boostMIL::WeakClassifier::classify().
    {
        double e = 0.0;
        std::list<Inputs*> ::const_iterator d_itr = dataset.begin();
        std::list<double> ::const_iterator w_itr = weights.begin();
        while(d_itr != dataset.begin())
        {
            if(classify(*d_itr) != (*d_itr)->getLabel())
                e += *w_itr;
            d_itr++;
        }
        return e;
    }
void AvgClassifier::fromStream (std::ifstream & fin) [virtual]
Loads a classifier from a string.
Parameters
the string encoding the classifier to be loaded
Implements iCub::boostMIL::WeakClassifier.
Definition at line 330 of file AvgClassifier.cpp.
References clear(), iCub::boostMIL::ClassifierFactory::create(), iCub::boostMIL::ClassifierFactory::instance(), and isReady().
{
    clear();
    fin.read((char*)&posweight,sizeof(double));
    fin.read((char*)&negweight,sizeof(double));
    fin.read((char*)&threshold,sizeof(double));
    fin.read((char*)&pool_size,sizeof(int));
    correct.resize(pool_size);
    wrong.resize(pool_size);
    alpha.resize(pool_size);
    pool.resize(pool_size);
    for(int i=0; i<pool_size; i++)
    {
        fin.read((char*)&correct[i],sizeof(double));
        fin.read((char*)&wrong[i],sizeof(double));
        alpha[i]=1.0/(1+exp((double)-(correct[i]-wrong[i])));
        //alpha[i]=log(sqrt((double)correct[i]/(wrong[i]+0.000001)));
        int size_of_type;
        fin.read((char*)&size_of_type,sizeof(int));
        char *wc_type=new char[size_of_type+1];
        fin.read((char*)wc_type,size_of_type*sizeof(char));
        wc_type[size_of_type]='\0';
        pool[i]=ClassifierFactory::instance().create(wc_type);
        delete [] wc_type;
        pool[i]->fromStream(fin);
    }
    isReady();
}
void AvgClassifier::fromString (const std::string & str) [virtual]
Loads a classifier from a string.
Parameters
the string encoding the classifier to be loaded
Implements iCub::boostMIL::WeakClassifier.
Definition at line 402 of file AvgClassifier.cpp.
References clear(), iCub::boostMIL::ClassifierFactory::instance(), isReady(), and iCub::boostMIL::WeakClassifier::type.
{
    clear();
    yarp::os::Bottle bLoader(str.c_str());
    type=bLoader.find("type").asString().c_str();
    posweight=bLoader.find("posweight").asDouble();
    negweight=bLoader.find("negweight").asDouble();
    threshold=bLoader.find("threshold").asDouble();
    yarp::os::Bottle *bPool=bLoader.find("pool").asList();
    pool_size=bPool->size();
    for(int i=0; i<pool_size; i++)
    {
        yarp::os::Bottle *bElement=bPool->get(i).asList();
        correct.push_back(bElement->find("correct").asDouble());
        wrong.push_back(bElement->find("wrong").asDouble());
        yarp::os::Bottle *bWL=bElement->find("weak_classifier").asList();
        pool.push_back(ClassifierFactory::instance().create(bWL->find("type").asString().c_str()));
        pool.back()->fromString(bWL->toString().c_str());
    }
    isReady();
}
double iCub::boostMIL::WeakClassifier::getError () const [inline], [inherited]
Returns the current error exhibited by the classifier.
Returns
the current error.
Definition at line 140 of file WeakClassifier.h.
References iCub::boostMIL::WeakClassifier::error.
Referenced by iCub::boostMIL::AdaBoost::train(), and iCub::boostMIL::OnlineBoost::update().
{return error;}
std::string iCub::boostMIL::WeakClassifier::getType () const [inline], [inherited]
Returns the classifier type information.
Returns
the type of the classifier
Definition at line 133 of file WeakClassifier.h.
References iCub::boostMIL::WeakClassifier::type.
Referenced by iCub::boostMIL::ClassifierFactory::registerClassifier(), iCub::boostMIL::SelectorClassifier::toStream(), iCub::boostMIL::OnlineBoost::toStream(), iCub::boostMIL::OnlineSupport::toStream(), toStream(), and iCub::boostMIL::StrongClassifier::toStream().
{return type;}
bool AvgClassifier::isReady () [virtual]
Updates the classifier and verifies if it is ready to be trained and to classify.
Returns
true if and only if the classifier is ready.
Implements iCub::boostMIL::WeakClassifier.
Definition at line 151 of file AvgClassifier.cpp.
References iCub::boostMIL::WeakClassifier::ready.
Referenced by fromStream(), and fromString().
{
    ready = true;
    //if the selector is not empty
    if(pool_size)
    {
        
        //fill the pool with new WeakClassifiers with the elements in the function_space list
        while(pool.size() < (unsigned) pool_size && function_space->size())
        {
            pool.push_back(function_space->front());
            function_space->pop_front();
        }
        //if the selector is still not completly filled it is not ready
        if(pool.size() != pool_size)
            ready = false;
        
        for(unsigned int i = 0; i < pool.size(); i++)
            if(!pool[i]->isReady()) ready = false;
    }
    else
        ready = false;
    return ready;
}
double AvgClassifier::margin (const Inputs * input, Output * output) const [virtual]
Margin given the input.
Parameters
input the input to classify.
Returns
the margin
Reimplemented from iCub::boostMIL::WeakClassifier.
Definition at line 125 of file AvgClassifier.cpp.
References iCub::boostMIL::WeakClassifier::ready.
Referenced by classify().
{
    double sum=0.0;
    if(ready)
    {
        for(int i=0; i<pool_size; i++)
        {
            double w=alpha[i]>0.0?alpha[i]:0.0;
            sum+=w*(0.5*(pool[i]->classify(input,output)+1)); //0 1 instead of -1 1
        }
    }
    return sum;
}
void AvgClassifier::toStream (std::ofstream & fout) const [virtual]
Encodes the classifier in a single string.
Implements iCub::boostMIL::WeakClassifier.
Definition at line 301 of file AvgClassifier.cpp.
References iCub::boostMIL::WeakClassifier::getType(), and iCub::boostMIL::WeakClassifier::ready.
{
    if(ready)
    {
        fout.write((char*)&posweight,sizeof(double));
        fout.write((char*)&negweight,sizeof(double));
        fout.write((char*)&threshold,sizeof(double));
        fout.write((char*)&pool_size,sizeof(int));
        for(int i=0; i<pool_size; i++)
        {
            fout.write((char*)&correct[i],sizeof(double));
            fout.write((char*)&wrong[i],sizeof(double));
            int size_of_type=pool[i]->getType().size();
            fout.write((char*)&size_of_type,sizeof(int));
            char *wc_type=new char[size_of_type+1];
            sprintf(wc_type,"%s",pool[i]->getType().c_str());
            fout.write((char*)wc_type,size_of_type*sizeof(char));
            delete [] wc_type;
            pool[i]->toStream(fout);
        }
    }
}
std::string AvgClassifier::toString () const [virtual]
Encodes the classifier in a single string.
Returns
a string encoding the current classifier form
Implements iCub::boostMIL::WeakClassifier.
Definition at line 371 of file AvgClassifier.cpp.
References iCub::boostMIL::WeakClassifier::ready, and iCub::boostMIL::WeakClassifier::type.
{
    if(ready)
    {
        std::stringstream strstr;
        strstr << "(type " << type << ") ";
        strstr << "(posweight " << posweight << ") ";
        strstr << "(negweight " << negweight << ") ";
        strstr << "(threshold " << threshold << ") ";
        strstr << "(pool (";
        for(unsigned int i=0; i<pool.size(); i++)
        {
            strstr << "(";
            strstr << "(correct " << correct[i] << ") ";
            strstr << "(wrong " << wrong[i] << ") ";
            strstr << "(weak_classifier (" << pool[i]->toString() << "))";
            strstr << ") ";
        }
        strstr << "))";
        return strstr.str().c_str();
    }
    else
        return "";
}
virtual void iCub::boostMIL::AvgClassifier::update (const Inputs * input, double & weight) [virtual]
Updates the classifier with respect to an input with associated weight.
Usually an online method.
Parameters
input the input.
the relevance weight associated to the given input.
Implements iCub::boostMIL::WeakClassifier.
The documentation for this class was generated from the following files:
C:/dev/icub-contrib-iit/boost-mil/lib/include/iCub/boostMIL/AvgClassifier.h
C:/dev/icub-contrib-iit/boost-mil/lib/src/AvgClassifier.cpp