iCub::boostMIL::StrongClassifier Class Reference
Strong Classifier The result of the training process.
#include <StrongClassifier.h>
Public Member Functions
StrongClassifier (const std::string &_type, yarp::os::ResourceFinder &_resource)
Constructor.
virtual ~StrongClassifier ()
Virtual Destructor.
virtual int getSize ()
Returns the current size of the List of WeakClassifiers.
virtual void clear ()
Clear Method.
double margin (const Inputs *input, Output *output=NULL) const
Computes the margin of the given input.
void printAlphas (FILE *f)
Prints the weights of all classifiers on a file.
virtual int classify (const Inputs *input, Output *output=NULL) const
Classifies the given input.
virtual StrongClassifier * create () const =0
Virtual Constructor.
virtual bool isReady ()=0
Updates the classifier and verifies if it is ready to be trained and to classify.
virtual void update (const Inputs *input, double &weight)=0
Updates the classifier with respect to an input with associated weight.
virtual void train (const std::list< Inputs * > &training_set)=0
Trains the classifier with respect to a list of inputs.
virtual void train (const Inputs *input, double weigth=1.0)=0
Trains the classifier with respect to a single input.
virtual void initialize (const Inputs *initializer)
For strong classifiers it does nothing (must be implemented in children)
virtual void initialize (const std::list< Inputs * > &initializer)
For strong classifiers it does nothing (must be implemented in children)lassifiers.
virtual std::string toString () const
Encodes the classifier in a single string.
virtual void fromString (const std::string &str)
Loads a classifier from a string.
virtual void toStream (std::ofstream &fout) const
Puts the classifier in a binary file stream.
virtual void fromStream (std::ifstream &str)
Loads a classifier from a binary file stream.
virtual bool saveAsString (const std::string &path) const
Saves the strong classifier in a single string.
virtual bool loadAsString (const std::string &path)
Loads a previously saved strong classifier.
virtual bool save (const std::string &path) const
Saves the strong classifier.
virtual bool load (const std::string &path)
Loads a previously saved strong classifier.
std::string getType () const
Returns the classifier type information.
double getError () const
Returns the current error exhibited by the classifier.
virtual std::list< WeakClassifier * > * pack (const Inputs *input) const
Extract the input information relative to this classifier type and creates a list of WeakClassifiers from it.
virtual double error_rate (const std::list< Inputs * > &dataset)
Returns the error rate of the classifier over a given dataset assuming uniform weight distribution.
virtual double error_rate (const std::list< Inputs * > &dataset, const std::list< double > &weights)
Returns the error rate of the classifier over a given dataset with specified weight distribution.
Protected Attributes
std::vector< WeakClassifier * > weak_classifiers
List of the WeakClassifiers contributing the decision function of the StrongClassifier.
std::vector< double > alphas
List of relevance weight for the WeakClassifier contributing the decision function of the StrongClassifier.
std::deque< WeakClassifier * > function_space
List of WeakClassifiers available to train the StrongClassifier.
yarp::os::ResourceFinder & resource
Resource containing the parameters information.
std::string type
The type associated to the WeakClassifier.
double error
Last computed error.
bool ready
Checks if the WeakClassifier has been initialized.
bool verbose
Allows prints by the boostMIL library.
Detailed Description
Strong Classifier The result of the training process.
The strong classifier learns how to linearly combine the output of a family of weak classifiers in order to provide predictions for.
Definition at line 56 of file StrongClassifier.h.
Constructor & Destructor Documentation
iCub::boostMIL::StrongClassifier::StrongClassifier (const std::string & _type, yarp::os::ResourceFinder & _resource) [inline]
Constructor.
Parameters
_type type of the classifier. It is needed to associate particular inputs and to clone via the ClassifierFactory.
_resource container for the classifier parameters.
Definition at line 84 of file StrongClassifier.h.
        :WeakClassifier(_type,_resource){}
Member Function Documentation
int StrongClassifier::classify (const Inputs * input, Output * output = NULL) const [virtual]
Classifies the given input.
Parameters
input the input to classify.
Returns
the sign of the margin. Returns 0 if the margin is 0.
Implements iCub::boostMIL::WeakClassifier.
Definition at line 73 of file StrongClassifier.cpp.
References margin(), and iCub::boostMIL::WeakClassifier::ready.
Referenced by iCub::boostMIL::OnlineBoost::update(), and iCub::boostMIL::OnlineSupport::update().
{
    if(!ready)
    {
        if(output!=NULL)
            output->setLabel(0);
        return 0;
    }
    int label;
    double m = margin(input,output);
    if(m == 0.0)
        label=0;
    if(m > 0.0)
        label=1;
    else
        label=-1;
    if(output!=NULL)
        output->setLabel(label);
    return label;
}
void StrongClassifier::clear () [virtual]
Clear Method.
Returns the classifier to its original condition (Pre-initialization).
Implements iCub::boostMIL::WeakClassifier.
Reimplemented in iCub::boostMIL::OnlineSupport, iCub::boostMIL::OnlineBoost, and iCub::boostMIL::AdaBoost.
Definition at line 30 of file StrongClassifier.cpp.
References alphas, function_space, iCub::boostMIL::WeakClassifier::ready, and weak_classifiers.
Referenced by iCub::boostMIL::AdaBoost::clear(), iCub::boostMIL::OnlineBoost::clear(), iCub::boostMIL::OnlineSupport::clear(), load(), loadAsString(), and ~StrongClassifier().
{
    ready = false;
    alphas.clear();
    while(weak_classifiers.size())
    {
        delete weak_classifiers.back();
        weak_classifiers.pop_back();
    }
    while(function_space.size())
    {
        delete function_space.back();
        function_space.pop_back();
    }
}
virtual double iCub::boostMIL::WeakClassifier::error_rate (const std::list< Inputs * > & dataset) [inline], [virtual], [inherited]
Returns the error rate of the classifier over a given dataset assuming uniform weight distribution.
Parameters
dataset the datataset over which compute the error rate.
Returns
the error rate.
Definition at line 158 of file WeakClassifier.h.
    {
        std::list<double> weights(dataset.size(),1.0/dataset.size());
        return error_rate(dataset,weights);
    }
virtual double iCub::boostMIL::WeakClassifier::error_rate (const std::list< Inputs * > & dataset, const std::list< double > & weights) [inline], [virtual], [inherited]
Returns the error rate of the classifier over a given dataset with specified weight distribution.
Parameters
dataset the datataset over which compute the error rate.
weights the weight distribution over the given dataset.
Returns
the error rate.
Definition at line 171 of file WeakClassifier.h.
References iCub::boostMIL::WeakClassifier::classify().
    {
        double e = 0.0;
        std::list<Inputs*> ::const_iterator d_itr = dataset.begin();
        std::list<double> ::const_iterator w_itr = weights.begin();
        while(d_itr != dataset.begin())
        {
            if(classify(*d_itr) != (*d_itr)->getLabel())
                e += *w_itr;
            d_itr++;
        }
        return e;
    }
void StrongClassifier::fromStream (std::ifstream & str) [virtual]
Loads a classifier from a binary file stream.
Parameters
the string encoding the classifier to be loaded
Implements iCub::boostMIL::WeakClassifier.
Reimplemented in iCub::boostMIL::OnlineSupport, and iCub::boostMIL::OnlineBoost.
Definition at line 113 of file StrongClassifier.cpp.
References alphas, iCub::boostMIL::ClassifierFactory::create(), iCub::boostMIL::ClassifierFactory::instance(), isReady(), and weak_classifiers.
Referenced by load().
{
    size_t wc_size;
    fin.read((char*)&wc_size,sizeof(size_t));
    alphas.resize(wc_size);
    weak_classifiers.resize(wc_size);
    for(size_t i=0; i<wc_size; i++)
    {
        fin.read((char*)&alphas[i],sizeof(double));
        int size_of_type;
        fin.read((char*)&size_of_type,sizeof(int));
        char *wc_type=new char[size_of_type+1];
        fin.read((char*)wc_type,size_of_type*sizeof(char));
        weak_classifiers[i]=ClassifierFactory::instance().create(wc_type);
        delete [] wc_type;
        weak_classifiers[i]->fromStream(fin);
    }
    isReady();
}
void StrongClassifier::fromString (const std::string & str) [virtual]
Loads a classifier from a string.
Parameters
the string encoding the classifier to be loaded
Implements iCub::boostMIL::WeakClassifier.
Reimplemented in iCub::boostMIL::OnlineSupport, and iCub::boostMIL::OnlineBoost.
Definition at line 166 of file StrongClassifier.cpp.
References alphas, create(), iCub::boostMIL::ClassifierFactory::instance(), isReady(), and weak_classifiers.
Referenced by loadAsString().
{
    yarp::os::Bottle bLoader(str.c_str());
    for(int i=0; i<bLoader.size(); i++)
    {
        alphas.push_back(bLoader.get(i).asList()->find("alpha").asDouble());
        yarp::os::Bottle *bWL=bLoader.get(i).asList()->find("weak_classifier").asList();
        weak_classifiers.push_back(ClassifierFactory::instance().create(bWL->find("type").asString().c_str(
      )));
        weak_classifiers.back()->fromString(bWL->toString().c_str());
    }
    isReady();
}
double iCub::boostMIL::WeakClassifier::getError () const [inline], [inherited]
Returns the current error exhibited by the classifier.
Returns
the current error.
Definition at line 140 of file WeakClassifier.h.
References iCub::boostMIL::WeakClassifier::error.
Referenced by iCub::boostMIL::AdaBoost::train(), and iCub::boostMIL::OnlineBoost::update().
{return error;}
std::string iCub::boostMIL::WeakClassifier::getType () const [inline], [inherited]
Returns the classifier type information.
Returns
the type of the classifier
Definition at line 133 of file WeakClassifier.h.
References iCub::boostMIL::WeakClassifier::type.
Referenced by iCub::boostMIL::ClassifierFactory::registerClassifier(), iCub::boostMIL::SelectorClassifier::toStream(), iCub::boostMIL::OnlineBoost::toStream(), iCub::boostMIL::OnlineSupport::toStream(), iCub::boostMIL::AvgClassifier::toStream(), and toStream().
{return type;}
virtual void iCub::boostMIL::StrongClassifier::initialize (const Inputs * initializer) [inline], [virtual]
For strong classifiers it does nothing (must be implemented in children)
Parameters
initializer the Input containing the weak classifiers.
Reimplemented in iCub::boostMIL::OnlineSupport, and iCub::boostMIL::OnlineBoost.
Definition at line 172 of file StrongClassifier.h.
{return;}
virtual void iCub::boostMIL::StrongClassifier::initialize (const std::list< Inputs * > & initializer) [inline], [virtual]
For strong classifiers it does nothing (must be implemented in children)lassifiers.
Parameters
initializer the Input list containing the weak classifiers.
Reimplemented in iCub::boostMIL::OnlineSupport, and iCub::boostMIL::OnlineBoost.
Definition at line 179 of file StrongClassifier.h.
{return;}
virtual bool iCub::boostMIL::StrongClassifier::isReady () [pure virtual]
Updates the classifier and verifies if it is ready to be trained and to classify.
Returns
true if and only if the classifier is ready.
Implements iCub::boostMIL::WeakClassifier.
Implemented in iCub::boostMIL::OnlineSupport, iCub::boostMIL::OnlineBoost, and iCub::boostMIL::AdaBoost.
Referenced by fromStream(), and fromString().
bool StrongClassifier::load (const std::string & path) [virtual]
Loads a previously saved strong classifier.
Parameters
path where the classifier has been saved.
Returns
true/false in case of success/failure
Definition at line 234 of file StrongClassifier.cpp.
References clear(), fromStream(), and loadAsString().
{
    this->clear();
    std::ifstream fin(path.c_str(),std::ios::in | std::ios::binary);
    if(!fin.is_open())
        return false;
    //check if the file was saved in string or binary format
    char c;
    fin.read(&c,sizeof(char));
    if(c=='(')
    {
        fin.close();
        this->loadAsString(path);
    }
    else
    {
        fin.seekg(0);
        this->fromStream(fin);
        fin.close();
    }
    return true;
}
bool StrongClassifier::loadAsString (const std::string & path) [virtual]
Loads a previously saved strong classifier.
The classifier must have been saved as a single string.
Parameters
path where the classifier has been saved.
Returns
true/false in case of success/failure
Definition at line 196 of file StrongClassifier.cpp.
References clear(), and fromString().
Referenced by load().
{
    this->clear();
    std::ifstream fin(path.c_str());
    if(!fin.is_open())
        return false;
    std::stringstream strstr;
    strstr<<fin.rdbuf();
    std::string str=strstr.str().c_str();
    this->fromString(str);
    fin.close();
    return true;
}
double StrongClassifier::margin (const Inputs * input, Output * output = NULL) const [virtual]
Computes the margin of the given input.
The margin is the response of the StrongClassifier decision function to the given input.
Parameters
input the input provided to the classifier.
Returns
the margin of the given input scaled between 0 and 1.
Reimplemented from iCub::boostMIL::WeakClassifier.
Definition at line 51 of file StrongClassifier.cpp.
References alphas, and weak_classifiers.
Referenced by classify().
{
    double s = 0.0;
    double a=0.0;
    for(unsigned int i = 0; i < weak_classifiers.size(); i++)
    {
        //double ai=alphas[i]>0.0?alphas[i]:0.0;
        //s+=ai*weak_classifiers[i]->classify(input,output);
        s+=alphas[i]*weak_classifiers[i]->classify(input,output);
        //a+=ai;
        a+=fabs(alphas[i]);
    }
    return (s+a)/(2*a);
}
virtual std::list<WeakClassifier*>* iCub::boostMIL::WeakClassifier::pack (const Inputs * input) const [inline], [virtual], [inherited]
Extract the input information relative to this classifier type and creates a list of WeakClassifiers from it.
Used for online methods to create the space of hypothesys directly from training data. Usually returns a null pointer.
Parameters
input the input from which extract the WeakClassifiers.
Returns
a list of pointers to the WeakClassifiers extracted from the input.
Reimplemented in iCub::boostMIL::MILClassifier.
Definition at line 150 of file WeakClassifier.h.
{return NULL;}
void StrongClassifier::printAlphas (FILE * f)
Prints the weights of all classifiers on a file.
Parameters
input the input provided to the classifier.
Returns
the margin of the given input. It returns 0 if the classifier is not ready yet to classify the input.
Definition at line 67 of file StrongClassifier.cpp.
References alphas.
{
    for(unsigned int i = 0; i < alphas.size(); i++)
        fprintf(f,"%f\n",alphas[i]);
}
bool StrongClassifier::save (const std::string & path) const [virtual]
Saves the strong classifier.
Parameters
path where the classifier has to be saved.
Returns
true/false in case of success/failure
Definition at line 220 of file StrongClassifier.cpp.
References toStream().
{
    std::ofstream fout(path.c_str(),std::ios::out | std::ios::binary);
    if(!fout.is_open())
        return false;
    this->toStream(fout);
    fout.close();
    return true;
}
bool StrongClassifier::saveAsString (const std::string & path) const [virtual]
Saves the strong classifier in a single string.
Parameters
path where the classifier has to be saved.
Returns
true/false in case of success/failure
Definition at line 183 of file StrongClassifier.cpp.
References toString().
{
    std::ofstream fout(path.c_str());
    if(!fout.is_open())
        return false;
    fout << this->toString();
    return true;
}
void StrongClassifier::toStream (std::ofstream & fout) const [virtual]
Puts the classifier in a binary file stream.
Implements iCub::boostMIL::WeakClassifier.
Reimplemented in iCub::boostMIL::OnlineSupport, and iCub::boostMIL::OnlineBoost.
Definition at line 140 of file StrongClassifier.cpp.
References alphas, iCub::boostMIL::WeakClassifier::getType(), and weak_classifiers.
Referenced by save().
{
    //write the size of the list fo weak classifiers
    size_t wc_size=this->weak_classifiers.size();
    fout.write((char*)&wc_size,sizeof(size_t));
    for(size_t i=0; i<wc_size; i++)
    {
        fout.write((char*)&alphas[i],sizeof(double));
        int size_of_type=weak_classifiers[i]->getType().size();
        fout.write((char*)&size_of_type,sizeof(int));
        char *wc_type=new char[size_of_type+1];
        sprintf(wc_type,"%s",weak_classifiers[i]->getType().c_str());
        wc_type[size_of_type]='\0';
        fout.write((char*)wc_type,size_of_type*sizeof(char));
        delete [] wc_type;
        weak_classifiers[i]->toStream(fout);
    }
}
std::string StrongClassifier::toString () const [virtual]
Encodes the classifier in a single string.
Returns
a string encoding the current classifier form
Implements iCub::boostMIL::WeakClassifier.
Definition at line 102 of file StrongClassifier.cpp.
References alphas, and weak_classifiers.
Referenced by saveAsString().
{
    std::stringstream strstr;
    for(unsigned int i = 0; i < this->weak_classifiers.size(); i++)
        strstr << "((alpha " << alphas[i] << ") (weak_classifier (" <<
      weak_classifiers[i]->toString() << "))) " << std::endl;
    return strstr.str().c_str();
}
virtual void iCub::boostMIL::StrongClassifier::train (const std::list< Inputs * > & training_set) [pure virtual]
Trains the classifier with respect to a list of inputs.
Parameters
training_set the list of inputs over which train the classifier.
Implemented in iCub::boostMIL::OnlineSupport, iCub::boostMIL::OnlineBoost, and iCub::boostMIL::AdaBoost.
virtual void iCub::boostMIL::StrongClassifier::train (const Inputs * input, double weigth = 1.0) [pure virtual]
Trains the classifier with respect to a single input.
Usually an online method.
Parameters
input the inputs over which train the classifier.
Implemented in iCub::boostMIL::OnlineSupport, and iCub::boostMIL::OnlineBoost.
virtual void iCub::boostMIL::StrongClassifier::update (const Inputs * input, double & weight) [pure virtual]
Updates the classifier with respect to an input with associated weight.
Usually an online method.
Parameters
input the input.
the relevance weight associated to the given input.
Implements iCub::boostMIL::WeakClassifier.
Implemented in iCub::boostMIL::OnlineSupport, and iCub::boostMIL::OnlineBoost.
The documentation for this class was generated from the following files:
C:/dev/icub-contrib-iit/boost-mil/lib/include/iCub/boostMIL/StrongClassifier.h
C:/dev/icub-contrib-iit/boost-mil/lib/src/StrongClassifier.cpp