iCub::boostMIL::WeakClassifier Class Reference
Weak Classifier The basic element of boosting.
#include <WeakClassifier.h>
Public Member Functions
WeakClassifier (const std::string &_type, yarp::os::ResourceFinder &_resource)
Constructor.
WeakClassifier (const WeakClassifier &wc)
Copy Constructor.
virtual ~WeakClassifier ()
Virtual Destructor.
virtual void clear ()=0
Clear Method.
std::string getType () const
Returns the classifier type information.
double getError () const
Returns the current error exhibited by the classifier.
virtual std::list< WeakClassifier * > * pack (const Inputs *input) const
Extract the input information relative to this classifier type and creates a list of WeakClassifiers from it.
virtual double error_rate (const std::list< Inputs * > &dataset)
Returns the error rate of the classifier over a given dataset assuming uniform weight distribution.
virtual double error_rate (const std::list< Inputs * > &dataset, const std::list< double > &weights)
Returns the error rate of the classifier over a given dataset with specified weight distribution.
virtual std::string toString () const =0
Encodes the classifier in a single string.
virtual void fromString (const std::string &str)=0
Loads a classifier from a string.
virtual void toStream (std::ofstream &fout) const =0
Encodes the classifier in a single string.
virtual void fromStream (std::ifstream &fin)=0
Loads a classifier from a string.
virtual void update (const Inputs *input, double &weight)=0
Updates the classifier with respect to an input with associated weight.
virtual bool isReady ()=0
Updates the classifier and verifies if it is ready to be trained and to classify.
virtual int classify (const Inputs *input, Output *output=NULL) const =0
Classifies the given input.
virtual double margin (const Inputs *input, Output *output=NULL) const
Margin, in general it is the same as classify.
virtual WeakClassifier * create () const =0
Virtual Constructor.
Protected Attributes
yarp::os::ResourceFinder & resource
Resource containing the parameters information.
std::string type
The type associated to the WeakClassifier.
double error
Last computed error.
bool ready
Checks if the WeakClassifier has been initialized.
bool verbose
Allows prints by the boostMIL library.
Detailed Description
Weak Classifier The basic element of boosting.
A weak classifier is a binary function which takes an input X and returns a positive (1) or negative (-1) output.
Definition at line 58 of file WeakClassifier.h.
Constructor & Destructor Documentation
iCub::boostMIL::WeakClassifier::WeakClassifier (const std::string & _type, yarp::os::ResourceFinder & _resource) [inline]
Constructor.
Parameters
_type type of the classifier. It is needed to associate particular inputs and to clone via the ClassifierFactory.
_resource container for the classifier parameters.
Definition at line 104 of file WeakClassifier.h.
      :type(_type),resource(_resource)
    {}
iCub::boostMIL::WeakClassifier::WeakClassifier (const WeakClassifier & wc) [inline]
Copy Constructor.
Parameters
wc the WeakClassifier from which the copy is instantiated.
Definition at line 113 of file WeakClassifier.h.
        :type(wc.type),resource(wc.resource)
    {}
Member Function Documentation
virtual int iCub::boostMIL::WeakClassifier::classify (const Inputs * input, Output * output = NULL) const [pure virtual]
Classifies the given input.
Parameters
input the input to classify.
Returns
1,-1 or 0 if the classifier classifies the input (respectively): positive, negative or undetermined (e.g. the classifier is not ready to classify yet).
Implemented in iCub::boostMIL::AvgClassifier, iCub::boostMIL::MILClassifier, iCub::boostMIL::SelectorClassifier, and iCub::boostMIL::StrongClassifier.
Referenced by error_rate(), margin(), and iCub::boostMIL::AdaBoost::train().
virtual void iCub::boostMIL::WeakClassifier::clear () [pure virtual]
Clear Method.
Returns the classifier to its original condition (Pre-initialization).
Implemented in iCub::boostMIL::AvgClassifier, iCub::boostMIL::MILClassifier, iCub::boostMIL::OnlineSupport, iCub::boostMIL::SelectorClassifier, iCub::boostMIL::OnlineBoost, iCub::boostMIL::StrongClassifier, and iCub::boostMIL::AdaBoost.
virtual double iCub::boostMIL::WeakClassifier::error_rate (const std::list< Inputs * > & dataset) [inline], [virtual]
Returns the error rate of the classifier over a given dataset assuming uniform weight distribution.
Parameters
dataset the datataset over which compute the error rate.
Returns
the error rate.
Definition at line 158 of file WeakClassifier.h.
    {
        std::list<double> weights(dataset.size(),1.0/dataset.size());
        return error_rate(dataset,weights);
    }
virtual double iCub::boostMIL::WeakClassifier::error_rate (const std::list< Inputs * > & dataset, const std::list< double > & weights) [inline], [virtual]
Returns the error rate of the classifier over a given dataset with specified weight distribution.
Parameters
dataset the datataset over which compute the error rate.
weights the weight distribution over the given dataset.
Returns
the error rate.
Definition at line 171 of file WeakClassifier.h.
References classify().
    {
        double e = 0.0;
        std::list<Inputs*> ::const_iterator d_itr = dataset.begin();
        std::list<double> ::const_iterator w_itr = weights.begin();
        while(d_itr != dataset.begin())
        {
            if(classify(*d_itr) != (*d_itr)->getLabel())
                e += *w_itr;
            d_itr++;
        }
        return e;
    }
virtual void iCub::boostMIL::WeakClassifier::fromStream (std::ifstream & fin) [pure virtual]
Loads a classifier from a string.
Parameters
the string encoding the classifier to be loaded
Implemented in iCub::boostMIL::StrongClassifier, iCub::boostMIL::MILClassifier, iCub::boostMIL::AvgClassifier, iCub::boostMIL::OnlineSupport, iCub::boostMIL::OnlineBoost, and iCub::boostMIL::SelectorClassifier.
virtual void iCub::boostMIL::WeakClassifier::fromString (const std::string & str) [pure virtual]
Loads a classifier from a string.
Parameters
the string encoding the classifier to be loaded
Implemented in iCub::boostMIL::StrongClassifier, iCub::boostMIL::AvgClassifier, iCub::boostMIL::OnlineSupport, iCub::boostMIL::OnlineBoost, iCub::boostMIL::MILClassifier, and iCub::boostMIL::SelectorClassifier.
double iCub::boostMIL::WeakClassifier::getError () const [inline]
Returns the current error exhibited by the classifier.
Returns
the current error.
Definition at line 140 of file WeakClassifier.h.
References error.
Referenced by iCub::boostMIL::AdaBoost::train(), and iCub::boostMIL::OnlineBoost::update().
{return error;}
std::string iCub::boostMIL::WeakClassifier::getType () const [inline]
Returns the classifier type information.
Returns
the type of the classifier
Definition at line 133 of file WeakClassifier.h.
References type.
Referenced by iCub::boostMIL::ClassifierFactory::registerClassifier(), iCub::boostMIL::SelectorClassifier::toStream(), iCub::boostMIL::OnlineBoost::toStream(), iCub::boostMIL::OnlineSupport::toStream(), iCub::boostMIL::AvgClassifier::toStream(), and iCub::boostMIL::StrongClassifier::toStream().
{return type;}
virtual bool iCub::boostMIL::WeakClassifier::isReady () [pure virtual]
Updates the classifier and verifies if it is ready to be trained and to classify.
Returns
true if and only if the classifier is ready.
Implemented in iCub::boostMIL::AvgClassifier, iCub::boostMIL::StrongClassifier, iCub::boostMIL::MILClassifier, iCub::boostMIL::OnlineSupport, iCub::boostMIL::OnlineBoost, iCub::boostMIL::AdaBoost, and iCub::boostMIL::SelectorClassifier.
virtual double iCub::boostMIL::WeakClassifier::margin (const Inputs * input, Output * output = NULL) const [inline], [virtual]
Margin, in general it is the same as classify.
Parameters
input the input to classify.
Returns
1,-1 or 0 if the classifier classifies the input (respectively): positive, negative or undetermined (e.g. the classifier is not ready to classify yet).
Reimplemented in iCub::boostMIL::OnlineSupport, iCub::boostMIL::AvgClassifier, and iCub::boostMIL::StrongClassifier.
Definition at line 249 of file WeakClassifier.h.
References classify().
    {
        return classify(input,output);
    }
virtual std::list<WeakClassifier*>* iCub::boostMIL::WeakClassifier::pack (const Inputs * input) const [inline], [virtual]
Extract the input information relative to this classifier type and creates a list of WeakClassifiers from it.
Used for online methods to create the space of hypothesys directly from training data. Usually returns a null pointer.
Parameters
input the input from which extract the WeakClassifiers.
Returns
a list of pointers to the WeakClassifiers extracted from the input.
Reimplemented in iCub::boostMIL::MILClassifier.
Definition at line 150 of file WeakClassifier.h.
{return NULL;}
virtual void iCub::boostMIL::WeakClassifier::toStream (std::ofstream & fout) const [pure virtual]
Encodes the classifier in a single string.
Implemented in iCub::boostMIL::StrongClassifier, iCub::boostMIL::AvgClassifier, iCub::boostMIL::MILClassifier, iCub::boostMIL::OnlineSupport, iCub::boostMIL::OnlineBoost, and iCub::boostMIL::SelectorClassifier.
virtual std::string iCub::boostMIL::WeakClassifier::toString () const [pure virtual]
Encodes the classifier in a single string.
Returns
a string encoding the current classifier form
Implemented in iCub::boostMIL::StrongClassifier, iCub::boostMIL::AvgClassifier, iCub::boostMIL::MILClassifier, and iCub::boostMIL::SelectorClassifier.
virtual void iCub::boostMIL::WeakClassifier::update (const Inputs * input, double & weight) [pure virtual]
Updates the classifier with respect to an input with associated weight.
Usually an online method.
Parameters
input the input.
the relevance weight associated to the given input.
Implemented in iCub::boostMIL::AvgClassifier, iCub::boostMIL::MILClassifier, iCub::boostMIL::OnlineSupport, iCub::boostMIL::OnlineBoost, iCub::boostMIL::StrongClassifier, and iCub::boostMIL::SelectorClassifier.
The documentation for this class was generated from the following file:
C:/dev/icub-contrib-iit/boost-mil/lib/include/iCub/boostMIL/WeakClassifier.h