iCub::boostMIL::ClassifierFactory Class Reference
Classifier Factory.
#include <ClassifierFactory.h>
Public Member Functions
void registerClassifier (WeakClassifier *h)
Registers a prototype object that can be used to create clones.
WeakClassifier * create (const std::string &type) const
Creates a new object given a specific type of key.
void pack (const Inputs *input, std::deque< WeakClassifier * > &function_space)
Static Public Member Functions
static ClassifierFactory & instance ()
An instance retrieval method that follows the Singleton pattern.
Protected Attributes
std::map< std::string, WeakClassifier * > map
The map that stores the key to object mapping.
Detailed Description
Classifier Factory.
Definition at line 49 of file ClassifierFactory.h.
Member Function Documentation
WeakClassifier* iCub::boostMIL::ClassifierFactory::create (const std::string & type) const [inline]
Creates a new object given a specific type of key.
The receiving end takes ownership of the returned pointer.
Parameters
key a key that identifies the type of machine
Returns
a copied object of the specified type
Exceptions
runtime error if no object has been registered with the same key
Definition at line 140 of file ClassifierFactory.h.
References iCub::boostMIL::WeakClassifier::create().
Referenced by iCub::boostMIL::SelectorClassifier::fromStream(), iCub::boostMIL::AvgClassifier::fromStream(), and iCub::boostMIL::StrongClassifier::fromStream().
    {
        if(this->map.count(type) == 0)
        {
            std::ostringstream buffer;
            buffer << "Could not find prototype '" << type
                   << "'; please specify a valid key.";
            throw std::runtime_error(buffer.str());
        }
        return this->map.find(type)->second->create();
    }
static ClassifierFactory& iCub::boostMIL::ClassifierFactory::instance () [inline], [static]
An instance retrieval method that follows the Singleton pattern.
Note that this implementation should not be considered thread safe and that problems may arise. However, due to the nature of the expected use this will not be likely to result in problems.
See http://www.oaklib.org/docs/oak/singleton.html for more information.
Returns
the singleton factory instance
Definition at line 97 of file ClassifierFactory.h.
Referenced by iCub::boostMIL::SelectorClassifier::fromStream(), iCub::boostMIL::AvgClassifier::fromStream(), iCub::boostMIL::StrongClassifier::fromStream(), iCub::boostMIL::SelectorClassifier::fromString(), iCub::boostMIL::AvgClassifier::fromString(), iCub::boostMIL::StrongClassifier::fromString(), iCub::boostMIL::OnlineBoost::initialize(), iCub::boostMIL::OnlineSupport::initialize(), iCub::boostMIL::OnlineBoost::update(), and iCub::boostMIL::OnlineSupport::update().
                                         {
        static ClassifierFactory instance;
        return instance;
    }
void iCub::boostMIL::ClassifierFactory::registerClassifier (WeakClassifier * h) [inline]
Registers a prototype object that can be used to create clones.
Strictly speaking, for this application the object only has to be able to return a new object of its own type, regardless of the internal state of that object.
Parameters
prototype the prototype object
Exceptions
runtime error if the name of the prototype is empty
runtime error if another object is registered with the same name
Definition at line 112 of file ClassifierFactory.h.
References iCub::boostMIL::WeakClassifier::getType().
                                               {
        assert(h != (WeakClassifier*) 0);
        if(h->getType() == "") {
            throw std::runtime_error("Cannot register classifier with empty type; please specify a unique
       key.");
        }
        if(this->map.count(h->getType()) > 0) {
            std::ostringstream buffer;
            buffer << "WeakClassifier of type '" << h->getType()
                   << "' has already been registered; please specify a unique key.";
            throw std::runtime_error(buffer.str());
        }
        this->map[h->getType()] = h;
        std::map<std::string,WeakClassifier*>::iterator itr = map.begin();
    }
The documentation for this class was generated from the following file:
C:/dev/icub-contrib-iit/boost-mil/lib/include/iCub/boostMIL/ClassifierFactory.h