iCub::boostMIL::SelectorClassifier Class Reference
Selector Classifier A weak classifier used for online learning which allows to keep perform feature selection.
#include <SelectorClassifier.h>
Public Member Functions
SelectorClassifier (const int &_type, yarp::os::ResourceFinder &_resource, std::deque< WeakClassifier * > *_function_space)
SelectorClassifier (const std::string &_type, yarp::os::ResourceFinder &_resource, std::deque< WeakClassifier * > *_function_space)
virtual bool isReady ()
Updates the classifier and verifies if it is ready to be trained and to classify.
virtual void clear ()
Clear Method.
virtual std::string toString () const
Encodes the classifier in a single string.
virtual void fromStream (std::ifstream &fin)
Loads a classifier from a string.
virtual void toStream (std::ofstream &fout) const
Encodes the classifier in a single string.
virtual void fromString (const std::string &str)
Loads a classifier from a string.
virtual int classify (const Inputs *input, Output *output) const
Classifies the given input.
virtual void update (const Inputs *input, double &weight)
Updates the classifier with respect to an input with associated weight.
std::string getType () const
Returns the classifier type information.
double getError () const
Returns the current error exhibited by the classifier.
virtual double error_rate (const std::list< Inputs * > &dataset)
Returns the error rate of the classifier over a given dataset assuming uniform weight distribution.
virtual double error_rate (const std::list< Inputs * > &dataset, const std::list< double > &weights)
Returns the error rate of the classifier over a given dataset with specified weight distribution.
virtual double margin (const Inputs *input, Output *output=NULL) const
Margin, in general it is the same as classify.
Protected Attributes
yarp::os::ResourceFinder & resource
Resource containing the parameters information.
std::string type
The type associated to the WeakClassifier.
double error
Last computed error.
bool ready
Checks if the WeakClassifier has been initialized.
bool verbose
Allows prints by the boostMIL library.
Detailed Description
Selector Classifier A weak classifier used for online learning which allows to keep perform feature selection.
Originally proposed in [PDF]
Definition at line 54 of file SelectorClassifier.h.
Member Function Documentation
int SelectorClassifier::classify (const Inputs * input, Output * output) const [virtual]
Classifies the given input.
Parameters
input the input to classify.
Returns
1,-1 or 0 if the classifier classifies the input (respectively): positive, negative or undetermined (e.g. the classifier is not ready to classify yet).
Implements iCub::boostMIL::WeakClassifier.
Definition at line 112 of file SelectorClassifier.cpp.
References iCub::boostMIL::WeakClassifier::ready.
{
    //The selector abstains from classifing if: it has not been initialized
    if(!ready || selected == -1 || asleep[selected] >= 0)
        return 0;
    else
        return pool[selected]->classify(input,output);
}
void SelectorClassifier::clear () [virtual]
Clear Method.
Returns the classifier to its original condition (Pre-initialization).
Implements iCub::boostMIL::WeakClassifier.
Definition at line 90 of file SelectorClassifier.cpp.
References iCub::boostMIL::WeakClassifier::ready.
Referenced by fromStream(), and fromString().
{
    ready=false;
    selected = -1;
    pool_size = 0;
    while(pool.size())
    {
        delete pool.back();
        pool.pop_back();
    }
    correct.clear();
    wrong.clear();
    asleep.clear();
    sleep_time = 0;
    abs_thresh = 0.0;
    rel_thresh = 0.0;
}
virtual double iCub::boostMIL::WeakClassifier::error_rate (const std::list< Inputs * > & dataset) [inline], [virtual], [inherited]
Returns the error rate of the classifier over a given dataset assuming uniform weight distribution.
Parameters
dataset the datataset over which compute the error rate.
Returns
the error rate.
Definition at line 158 of file WeakClassifier.h.
    {
        std::list<double> weights(dataset.size(),1.0/dataset.size());
        return error_rate(dataset,weights);
    }
virtual double iCub::boostMIL::WeakClassifier::error_rate (const std::list< Inputs * > & dataset, const std::list< double > & weights) [inline], [virtual], [inherited]
Returns the error rate of the classifier over a given dataset with specified weight distribution.
Parameters
dataset the datataset over which compute the error rate.
weights the weight distribution over the given dataset.
Returns
the error rate.
Definition at line 171 of file WeakClassifier.h.
References iCub::boostMIL::WeakClassifier::classify().
    {
        double e = 0.0;
        std::list<Inputs*> ::const_iterator d_itr = dataset.begin();
        std::list<double> ::const_iterator w_itr = weights.begin();
        while(d_itr != dataset.begin())
        {
            if(classify(*d_itr) != (*d_itr)->getLabel())
                e += *w_itr;
            d_itr++;
        }
        return e;
    }
void SelectorClassifier::fromStream (std::ifstream & fin) [virtual]
Loads a classifier from a string.
Parameters
the string encoding the classifier to be loaded
Implements iCub::boostMIL::WeakClassifier.
Definition at line 255 of file SelectorClassifier.cpp.
References clear(), iCub::boostMIL::ClassifierFactory::create(), iCub::boostMIL::ClassifierFactory::instance(), and isReady().
{
    clear();
    fin.read((char*)&selected,sizeof(int));
    fin.read((char*)&abs_thresh,sizeof(double));
    fin.read((char*)&rel_thresh,sizeof(double));
    fin.read((char*)&sleep_time,sizeof(int));
    fin.read((char*)&pool_size,sizeof(int));
    correct.resize(pool_size);
    wrong.resize(pool_size);
    asleep.resize(pool_size);
    pool.resize(pool_size);
    for(int i=0; i<pool_size; i++)
    {
        fin.read((char*)&correct[i],sizeof(double));
        fin.read((char*)&wrong[i],sizeof(double));
        fin.read((char*)&asleep[i],sizeof(int));
        int size_of_type;
        fin.read((char*)&size_of_type,sizeof(int));
        char *wc_type=new char[size_of_type+1];
        fin.read((char*)wc_type,size_of_type*sizeof(char));
        wc_type[size_of_type]='\0';
        pool[i]=ClassifierFactory::instance().create(wc_type);
        delete [] wc_type;
        pool[i]->fromStream(fin);
    }
    isReady();
}
void SelectorClassifier::fromString (const std::string & str) [virtual]
Loads a classifier from a string.
Parameters
the string encoding the classifier to be loaded
Implements iCub::boostMIL::WeakClassifier.
Definition at line 328 of file SelectorClassifier.cpp.
References clear(), iCub::boostMIL::ClassifierFactory::instance(), isReady(), and iCub::boostMIL::WeakClassifier::type.
{
    clear();
    yarp::os::Bottle bLoader(str.c_str());
    type=bLoader.find("type").asString().c_str();
    selected=bLoader.find("selected").asInt();
    abs_thresh=bLoader.find("abs_thresh").asDouble();
    rel_thresh=bLoader.find("rel_thresh").asDouble();
    sleep_time=bLoader.find("sleep_time").asInt();
    yarp::os::Bottle *bPool=bLoader.find("pool").asList();
    pool_size=bPool->size();
    for(int i=0; i<pool_size; i++)
    {
        yarp::os::Bottle *bElement=bPool->get(i).asList();
        correct.push_back(bElement->find("correct").asDouble());
        wrong.push_back(bElement->find("wrong").asDouble());
        asleep.push_back(bElement->find("asleep").asInt());
        yarp::os::Bottle *bWL=bElement->find("weak_classifier").asList();
        pool.push_back(ClassifierFactory::instance().create(bWL->find("type").asString().c_str()));
        pool.back()->fromString(bWL->toString().c_str());
    }
    isReady();
}
double iCub::boostMIL::WeakClassifier::getError () const [inline], [inherited]
Returns the current error exhibited by the classifier.
Returns
the current error.
Definition at line 140 of file WeakClassifier.h.
References iCub::boostMIL::WeakClassifier::error.
Referenced by iCub::boostMIL::AdaBoost::train(), and iCub::boostMIL::OnlineBoost::update().
{return error;}
std::string iCub::boostMIL::WeakClassifier::getType () const [inline], [inherited]
Returns the classifier type information.
Returns
the type of the classifier
Definition at line 133 of file WeakClassifier.h.
References iCub::boostMIL::WeakClassifier::type.
Referenced by iCub::boostMIL::ClassifierFactory::registerClassifier(), toStream(), iCub::boostMIL::OnlineBoost::toStream(), iCub::boostMIL::OnlineSupport::toStream(), iCub::boostMIL::AvgClassifier::toStream(), and iCub::boostMIL::StrongClassifier::toStream().
{return type;}
bool SelectorClassifier::isReady () [virtual]
Updates the classifier and verifies if it is ready to be trained and to classify.
Returns
true if and only if the classifier is ready.
Implements iCub::boostMIL::WeakClassifier.
Definition at line 121 of file SelectorClassifier.cpp.
References iCub::boostMIL::WeakClassifier::ready.
Referenced by fromStream(), fromString(), and update().
{
    ready = true;
    //if the selector is not empty
    if(pool_size)
    {
        //fill the pool with new WeakClassifiers with the elements in the function_space list
        while(pool.size() < (unsigned) pool_size && function_space->size())
        {
            pool.push_back(function_space->front());
            function_space->pop_front();
        }
        //if the selector is still not completly filled it is not ready
        if(pool.size() != pool_size)
            ready = false;
        for(unsigned int i = 0; i < pool.size(); i++)
            if(!pool[i]->isReady()) ready = false;
    }
    else
        ready = false;
    return ready;
}
virtual double iCub::boostMIL::WeakClassifier::margin (const Inputs * input, Output * output = NULL) const [inline], [virtual], [inherited]
Margin, in general it is the same as classify.
Parameters
input the input to classify.
Returns
1,-1 or 0 if the classifier classifies the input (respectively): positive, negative or undetermined (e.g. the classifier is not ready to classify yet).
Reimplemented in iCub::boostMIL::OnlineSupport, iCub::boostMIL::AvgClassifier, and iCub::boostMIL::StrongClassifier.
Definition at line 249 of file WeakClassifier.h.
References iCub::boostMIL::WeakClassifier::classify().
    {
        return classify(input,output);
    }
void SelectorClassifier::toStream (std::ofstream & fout) const [virtual]
Encodes the classifier in a single string.
Implements iCub::boostMIL::WeakClassifier.
Definition at line 224 of file SelectorClassifier.cpp.
References iCub::boostMIL::WeakClassifier::getType(), and iCub::boostMIL::WeakClassifier::ready.
{
    if(ready)
    {
        fout.write((char*)&selected,sizeof(int));
        fout.write((char*)&abs_thresh,sizeof(double));
        fout.write((char*)&rel_thresh,sizeof(double));
        fout.write((char*)&sleep_time,sizeof(int));
        fout.write((char*)&pool_size,sizeof(int));
        for(int i=0; i<pool_size; i++)
        {
            fout.write((char*)&correct[i],sizeof(double));
            fout.write((char*)&wrong[i],sizeof(double));
            fout.write((char*)&asleep[i],sizeof(int));
            int size_of_type=pool[i]->getType().size();
            fout.write((char*)&size_of_type,sizeof(int));
            char *wc_type=new char[size_of_type+1];
            sprintf(wc_type,"%s",pool[i]->getType().c_str());
            fout.write((char*)wc_type,size_of_type*sizeof(char));
            delete [] wc_type;
            pool[i]->toStream(fout);
        }
    }
}
std::string SelectorClassifier::toString () const [virtual]
Encodes the classifier in a single string.
Returns
a string encoding the current classifier form
Implements iCub::boostMIL::WeakClassifier.
Definition at line 295 of file SelectorClassifier.cpp.
References iCub::boostMIL::WeakClassifier::ready, and iCub::boostMIL::WeakClassifier::type.
{
    if(ready)
    {
        std::stringstream strstr;
        strstr << "(type " << type << ") ";
        strstr << "(selected " << selected << ") ";
        strstr << "(abs_thresh " << abs_thresh <<") ";
        strstr << "(rel_thresh " << rel_thresh <<") ";
        strstr << "(sleep_time " << sleep_time <<") ";
        strstr << "(pool (";
        for(unsigned int i=0; i<pool.size(); i++)
        {
            strstr << "(";
            strstr << "(correct " << correct[i] << ") ";
            strstr << "(wrong " << wrong[i] << ") ";
            strstr << "(asleep " << asleep[i] << ") ";
            strstr << "(weak_classifier (" << pool[i]->toString() << "))";
            strstr << ") ";
        }
        strstr << "))";
        return strstr.str().c_str();
    }
    else
        return "";
}
void SelectorClassifier::update (const Inputs * input, double & weight) [virtual]
Updates the classifier with respect to an input with associated weight.
Usually an online method.
Parameters
input the input.
the relevance weight associated to the given input.
Implements iCub::boostMIL::WeakClassifier.
Definition at line 150 of file SelectorClassifier.cpp.
References iCub::boostMIL::WeakClassifier::error, and isReady().
{
    if(isReady())
    {
        error = 1.0;
        std::vector<double> errors(pool.size());
        for(unsigned int i = 0; i < pool.size(); i++)
        {
            pool[i]->update(input,weight);
            //estimate the (online) error
            pool[i]->classify(input)==input->getLabel()?correct[i]++:wrong[i]++;
            errors[i] = wrong[i]/(correct[i]+wrong[i]);
            asleep[i]--;
            //keep track of the best WeakClassifier
            if(asleep[i] < 0 && errors[i] < error)
            {
                error = errors[i];
                selected = i;
            }
        }
        //handle unconsistencies of the trained WeakClassifiers
        if(selected>0 && !asleep[selected] && (error < 1e-6 || error > 0.5))
        {
            //debug
            std::cout << "this selector has best error " << this->error << std::endl;
        }
        //if needed, substitute bad performing Weak Classifiers
        for(unsigned int i = 0; i < pool.size(); i++)
        {
            if(asleep[i] < 0 && function_space->size() && substitute(errors[i]) && i != selected)
            {
                delete pool[i];
                pool[i] = randomSample();
                correct[i] = 1.0;
                wrong[i] = 1.0;
                asleep[i] = sleep_time;
            }
        }
    }
}
The documentation for this class was generated from the following files:
C:/dev/icub-contrib-iit/boost-mil/lib/include/iCub/boostMIL/SelectorClassifier.h
C:/dev/icub-contrib-iit/boost-mil/lib/src/SelectorClassifier.cpp