iCub::boostMIL::OnlineSupport Class Reference
Online Support A strong classifier which is trained online using the algorithm proposed by Oza (PDF)
#include <OnlineSupport.h>
Public Member Functions
OnlineSupport (yarp::os::ResourceFinder &_resource)
Constructor.
OnlineSupport (const int &_type, yarp::os::ResourceFinder &_resource)
Constructor.
OnlineSupport (const std::string &_type, yarp::os::ResourceFinder &_resource)
Constructor.
~OnlineSupport ()
Virtual Destructor.
virtual void clear ()
Clear Method.
virtual bool isReady ()
Updates the classifier and verifies if it is ready to be trained and to classify.
virtual OnlineSupport * create () const
Virtual Constructor.
virtual void initialize (const Inputs *initializer)
Initializes the online classifier with a bag of positive weak classifiers.
virtual void initialize (const std::list< Inputs * > &initializer)
Initializes the online classifier with a list of bags of positive weak classifiers.
virtual void toStream (std::ofstream &fout) const
Encodes the classifier in a single string.
virtual void fromStream (std::ifstream &str)
Loads a classifier from a string.
virtual void fromString (const std::string &str)
Loads a classifier from a string.
virtual void clearFunctionSpace ()
Clears the function space.
virtual void update (const Inputs *input, double &weight)
Updates the classifier with respect to an input with associated weight.
virtual void train (const std::list< Inputs * > &training_set)
Trains the classifier with respect to a list of inputs.
virtual void train (const Inputs *input, double weight=1.0)
Trains the classifier with respect to a single input.
virtual void randomizeFuncSpace ()
Randomizes the function space.
double margin (const Inputs *input, Output *output=NULL) const
Computes the margin of the given input.
virtual int getSize ()
Returns the current size of the List of WeakClassifiers.
void printAlphas (FILE *f)
Prints the weights of all classifiers on a file.
virtual int classify (const Inputs *input, Output *output=NULL) const
Classifies the given input.
virtual std::string toString () const
Encodes the classifier in a single string.
virtual bool saveAsString (const std::string &path) const
Saves the strong classifier in a single string.
virtual bool loadAsString (const std::string &path)
Loads a previously saved strong classifier.
virtual bool save (const std::string &path) const
Saves the strong classifier.
virtual bool load (const std::string &path)
Loads a previously saved strong classifier.
std::string getType () const
Returns the classifier type information.
double getError () const
Returns the current error exhibited by the classifier.
virtual std::list< WeakClassifier * > * pack (const Inputs *input) const
Extract the input information relative to this classifier type and creates a list of WeakClassifiers from it.
virtual double error_rate (const std::list< Inputs * > &dataset)
Returns the error rate of the classifier over a given dataset assuming uniform weight distribution.
virtual double error_rate (const std::list< Inputs * > &dataset, const std::list< double > &weights)
Returns the error rate of the classifier over a given dataset with specified weight distribution.
Protected Attributes
std::vector< WeakClassifier * > weak_classifiers
List of the WeakClassifiers contributing the decision function of the StrongClassifier.
std::vector< double > alphas
List of relevance weight for the WeakClassifier contributing the decision function of the StrongClassifier.
std::deque< WeakClassifier * > function_space
List of WeakClassifiers available to train the StrongClassifier.
yarp::os::ResourceFinder & resource
Resource containing the parameters information.
std::string type
The type associated to the WeakClassifier.
double error
Last computed error.
bool ready
Checks if the WeakClassifier has been initialized.
bool verbose
Allows prints by the boostMIL library.
Detailed Description
Online Support A strong classifier which is trained online using the algorithm proposed by Oza (PDF)
Definition at line 52 of file OnlineSupport.h.
Constructor & Destructor Documentation
OnlineSupport::OnlineSupport (yarp::os::ResourceFinder & _resource)
Constructor.
It assumes that the name of the Strong Classifier is 'online_boost'.
Parameters
_resource container for the classifier parameters.
Definition at line 40 of file OnlineSupport.cpp.
    :StrongClassifier("online_boost",_resource)
{
    initResource();
}
iCub::boostMIL::OnlineSupport::OnlineSupport (const int & _type, yarp::os::ResourceFinder & _resource)
Constructor.
Parameters
_type type of the classifier. It is needed to associate particular inputs and to clone via the ClassifierFactory.
_resource container for the classifier parameters.
OnlineSupport::OnlineSupport (const std::string & _type, yarp::os::ResourceFinder & _resource)
Constructor.
Parameters
_type type of the classifier. It is needed to associate particular inputs and to clone via the ClassifierFactory.
_resource container for the classifier parameters.
Definition at line 46 of file OnlineSupport.cpp.
    :StrongClassifier(_type,_resource)
{
    initResource();
}
Member Function Documentation
int StrongClassifier::classify (const Inputs * input, Output * output = NULL) const [virtual], [inherited]
Classifies the given input.
Parameters
input the input to classify.
Returns
the sign of the margin. Returns 0 if the margin is 0.
Implements iCub::boostMIL::WeakClassifier.
Definition at line 73 of file StrongClassifier.cpp.
References iCub::boostMIL::StrongClassifier::margin(), and iCub::boostMIL::WeakClassifier::ready.
Referenced by iCub::boostMIL::OnlineBoost::update(), and update().
{
    if(!ready)
    {
        if(output!=NULL)
            output->setLabel(0);
        return 0;
    }
    int label;
    double m = margin(input,output);
    if(m == 0.0)
        label=0;
    if(m > 0.0)
        label=1;
    else
        label=-1;
    if(output!=NULL)
        output->setLabel(label);
    return label;
}
void OnlineSupport::clear () [virtual]
Clear Method.
Returns the classifier to its original condition (Pre-initialization).
Reimplemented from iCub::boostMIL::StrongClassifier.
Definition at line 347 of file OnlineSupport.cpp.
References iCub::boostMIL::StrongClassifier::clear().
Referenced by fromStream(), fromString(), and ~OnlineSupport().
{
    StrongClassifier::clear();
    weak_classifiers_size = 0;
}
virtual double iCub::boostMIL::WeakClassifier::error_rate (const std::list< Inputs * > & dataset) [inline], [virtual], [inherited]
Returns the error rate of the classifier over a given dataset assuming uniform weight distribution.
Parameters
dataset the datataset over which compute the error rate.
Returns
the error rate.
Definition at line 158 of file WeakClassifier.h.
    {
        std::list<double> weights(dataset.size(),1.0/dataset.size());
        return error_rate(dataset,weights);
    }
virtual double iCub::boostMIL::WeakClassifier::error_rate (const std::list< Inputs * > & dataset, const std::list< double > & weights) [inline], [virtual], [inherited]
Returns the error rate of the classifier over a given dataset with specified weight distribution.
Parameters
dataset the datataset over which compute the error rate.
weights the weight distribution over the given dataset.
Returns
the error rate.
Definition at line 171 of file WeakClassifier.h.
References iCub::boostMIL::WeakClassifier::classify().
    {
        double e = 0.0;
        std::list<Inputs*> ::const_iterator d_itr = dataset.begin();
        std::list<double> ::const_iterator w_itr = weights.begin();
        while(d_itr != dataset.begin())
        {
            if(classify(*d_itr) != (*d_itr)->getLabel())
                e += *w_itr;
            d_itr++;
        }
        return e;
    }
void OnlineSupport::fromStream (std::ifstream & str) [virtual]
Loads a classifier from a string.
Parameters
the string encoding the classifier to be loaded
Reimplemented from iCub::boostMIL::StrongClassifier.
Definition at line 129 of file OnlineSupport.cpp.
References iCub::boostMIL::StrongClassifier::alphas, clear(), iCub::boostMIL::StrongClassifier::function_space, isReady(), iCub::boostMIL::WeakClassifier::resource, and iCub::boostMIL::StrongClassifier::weak_classifiers.
{
    clear();
    int wc_size;
    fin.read((char*)&wc_size,sizeof(int));
    weak_classifiers_size=wc_size;
    alphas.resize(wc_size);
    correct.resize(wc_size);
    wrong.resize(wc_size);
    weak_classifiers.resize(wc_size);
    for(int i=0; i<wc_size; i++)
    {
        fin.read((char*)&alphas[i],sizeof(double));
        fin.read((char*)&correct[i],sizeof(int));
        fin.read((char*)&wrong[i],sizeof(int));
        int size_of_type;
        fin.read((char*)&size_of_type,sizeof(int));
        char *wc_type=new char[size_of_type+1];
        fin.read((char*)wc_type,size_of_type*sizeof(char));
        wc_type[size_of_type]='\0';
        weak_classifiers[i]=new AvgClassifier(wc_type,resource,&function_space);
        delete [] wc_type;
        weak_classifiers[i]->fromStream(fin);
    }
    isReady();
}
void OnlineSupport::fromString (const std::string & str) [virtual]
Loads a classifier from a string.
Parameters
the string encoding the classifier to be loaded
Reimplemented from iCub::boostMIL::StrongClassifier.
Definition at line 192 of file OnlineSupport.cpp.
References iCub::boostMIL::StrongClassifier::alphas, clear(), iCub::boostMIL::StrongClassifier::function_space, isReady(), iCub::boostMIL::WeakClassifier::resource, and iCub::boostMIL::StrongClassifier::weak_classifiers.
{
    clear();
    yarp::os::Bottle bLoader;
    bLoader.fromString(str.c_str());
    weak_classifiers_size=bLoader.size();
    for(int i=0; i<bLoader.size(); i++)
    {
        alphas.push_back(bLoader.get(i).asList()->find("alpha").asDouble());
        correct.push_back((int)bLoader.get(i).asList()->find("correct").asDouble());
        wrong.push_back((int)bLoader.get(i).asList()->find("wrong").asDouble());
        yarp::os::Bottle *bSelector=bLoader.get(i).asList()->find("weak_classifier").asList();
        weak_classifiers.push_back(new AvgClassifier(bSelector->find("type").asString().c_str(),
      resource,&function_space));
        weak_classifiers.back()->fromString(bSelector->toString().c_str());
    }
    isReady();
}
double iCub::boostMIL::WeakClassifier::getError () const [inline], [inherited]
Returns the current error exhibited by the classifier.
Returns
the current error.
Definition at line 140 of file WeakClassifier.h.
References iCub::boostMIL::WeakClassifier::error.
Referenced by iCub::boostMIL::AdaBoost::train(), and iCub::boostMIL::OnlineBoost::update().
{return error;}
std::string iCub::boostMIL::WeakClassifier::getType () const [inline], [inherited]
Returns the classifier type information.
Returns
the type of the classifier
Definition at line 133 of file WeakClassifier.h.
References iCub::boostMIL::WeakClassifier::type.
Referenced by iCub::boostMIL::ClassifierFactory::registerClassifier(), iCub::boostMIL::SelectorClassifier::toStream(), iCub::boostMIL::OnlineBoost::toStream(), toStream(), iCub::boostMIL::AvgClassifier::toStream(), and iCub::boostMIL::StrongClassifier::toStream().
{return type;}
void OnlineSupport::initialize (const Inputs * initializer) [virtual]
Initializes the online classifier with a bag of positive weak classifiers.
Parameters
initializer the Input containing the weak classifiers.
Reimplemented from iCub::boostMIL::StrongClassifier.
Definition at line 113 of file OnlineSupport.cpp.
References iCub::boostMIL::StrongClassifier::function_space, and iCub::boostMIL::ClassifierFactory::instance().
{
    ClassifierFactory::instance().pack(initializer,function_space);
}
void OnlineSupport::initialize (const std::list< Inputs * > & initializer) [virtual]
Initializes the online classifier with a list of bags of positive weak classifiers.
Parameters
initializer the Input list containing the weak classifiers.
Reimplemented from iCub::boostMIL::StrongClassifier.
Definition at line 118 of file OnlineSupport.cpp.
References iCub::boostMIL::StrongClassifier::function_space, and iCub::boostMIL::ClassifierFactory::instance().
{
    for(std::list<Inputs*>::const_iterator itr=initializer.begin(); itr!=initializer.end(); itr++)
        ClassifierFactory::instance().pack((*itr),function_space);
    //shuffle the function_space
    random_shuffle(function_space.begin(),function_space.end());
}
bool OnlineSupport::isReady () [virtual]
Updates the classifier and verifies if it is ready to be trained and to classify.
Returns
true if and only if the classifier is ready.
Implements iCub::boostMIL::StrongClassifier.
Definition at line 81 of file OnlineSupport.cpp.
References iCub::boostMIL::WeakClassifier::ready, and iCub::boostMIL::StrongClassifier::weak_classifiers.
Referenced by fromStream(), fromString(), and update().
{
    //OnlineSupport is initialized if all the WeakClassifiers are initialized
    ready = true;
    if(weak_classifiers_size)
    {
        for(unsigned int i = 0; i < weak_classifiers.size(); i++)
             if(!weak_classifiers[i]->isReady()) ready = false;
    }
    else
        ready = false;
    return ready;
}
bool StrongClassifier::load (const std::string & path) [virtual], [inherited]
Loads a previously saved strong classifier.
Parameters
path where the classifier has been saved.
Returns
true/false in case of success/failure
Definition at line 234 of file StrongClassifier.cpp.
References iCub::boostMIL::StrongClassifier::clear(), iCub::boostMIL::StrongClassifier::fromStream(), and iCub::boostMIL::StrongClassifier::loadAsString().
{
    this->clear();
    std::ifstream fin(path.c_str(),std::ios::in | std::ios::binary);
    if(!fin.is_open())
        return false;
    //check if the file was saved in string or binary format
    char c;
    fin.read(&c,sizeof(char));
    if(c=='(')
    {
        fin.close();
        this->loadAsString(path);
    }
    else
    {
        fin.seekg(0);
        this->fromStream(fin);
        fin.close();
    }
    return true;
}
bool StrongClassifier::loadAsString (const std::string & path) [virtual], [inherited]
Loads a previously saved strong classifier.
The classifier must have been saved as a single string.
Parameters
path where the classifier has been saved.
Returns
true/false in case of success/failure
Definition at line 196 of file StrongClassifier.cpp.
References iCub::boostMIL::StrongClassifier::clear(), and iCub::boostMIL::StrongClassifier::fromString().
Referenced by iCub::boostMIL::StrongClassifier::load().
{
    this->clear();
    std::ifstream fin(path.c_str());
    if(!fin.is_open())
        return false;
    std::stringstream strstr;
    strstr<<fin.rdbuf();
    std::string str=strstr.str().c_str();
    this->fromString(str);
    fin.close();
    return true;
}
double OnlineSupport::margin (const Inputs * input, Output * output = NULL) const [virtual]
Computes the margin of the given input.
The margin is the response of the StrongClassifier decision function to the given input.
Parameters
input the input provided to the classifier.
Returns
the margin of the given input scaled between 0 and 1.
Reimplemented from iCub::boostMIL::WeakClassifier.
Definition at line 364 of file OnlineSupport.cpp.
References iCub::boostMIL::StrongClassifier::alphas, iCub::boostMIL::WeakClassifier::ready, and iCub::boostMIL::StrongClassifier::weak_classifiers.
{
    double sum=0.0;
    if(ready)
    {
        for(size_t i=0; i<weak_classifiers.size(); i++)
        {
            double w=alphas[i]>0.0?alphas[i]:0.0;
            sum+=w*(0.5*(weak_classifiers[i]->classify(input,output)+1)); //0 1 instead of -1 1
        }
    }
    return sum;
}
virtual std::list<WeakClassifier*>* iCub::boostMIL::WeakClassifier::pack (const Inputs * input) const [inline], [virtual], [inherited]
Extract the input information relative to this classifier type and creates a list of WeakClassifiers from it.
Used for online methods to create the space of hypothesys directly from training data. Usually returns a null pointer.
Parameters
input the input from which extract the WeakClassifiers.
Returns
a list of pointers to the WeakClassifiers extracted from the input.
Reimplemented in iCub::boostMIL::MILClassifier.
Definition at line 150 of file WeakClassifier.h.
{return NULL;}
void StrongClassifier::printAlphas (FILE * f) [inherited]
Prints the weights of all classifiers on a file.
Parameters
input the input provided to the classifier.
Returns
the margin of the given input. It returns 0 if the classifier is not ready yet to classify the input.
Definition at line 67 of file StrongClassifier.cpp.
References iCub::boostMIL::StrongClassifier::alphas.
{
    for(unsigned int i = 0; i < alphas.size(); i++)
        fprintf(f,"%f\n",alphas[i]);
}
void OnlineSupport::randomizeFuncSpace () [virtual]
Randomizes the function space.
Definition at line 355 of file OnlineSupport.cpp.
References iCub::boostMIL::StrongClassifier::function_space.
{
    random_shuffle(function_space.begin(),function_space.end());
}
bool StrongClassifier::save (const std::string & path) const [virtual], [inherited]
Saves the strong classifier.
Parameters
path where the classifier has to be saved.
Returns
true/false in case of success/failure
Definition at line 220 of file StrongClassifier.cpp.
References iCub::boostMIL::StrongClassifier::toStream().
{
    std::ofstream fout(path.c_str(),std::ios::out | std::ios::binary);
    if(!fout.is_open())
        return false;
    this->toStream(fout);
    fout.close();
    return true;
}
bool StrongClassifier::saveAsString (const std::string & path) const [virtual], [inherited]
Saves the strong classifier in a single string.
Parameters
path where the classifier has to be saved.
Returns
true/false in case of success/failure
Definition at line 183 of file StrongClassifier.cpp.
References iCub::boostMIL::StrongClassifier::toString().
{
    std::ofstream fout(path.c_str());
    if(!fout.is_open())
        return false;
    fout << this->toString();
    return true;
}
void OnlineSupport::toStream (std::ofstream & fout) const [virtual]
Encodes the classifier in a single string.
Reimplemented from iCub::boostMIL::StrongClassifier.
Definition at line 165 of file OnlineSupport.cpp.
References iCub::boostMIL::StrongClassifier::alphas, iCub::boostMIL::WeakClassifier::getType(), and iCub::boostMIL::StrongClassifier::weak_classifiers.
{
    //write the size of the list of weak classifiers
    int wc_size=this->weak_classifiers.size();
    fout.write((char*)&wc_size,sizeof(int));
    for(int i=0; i<wc_size; i++)
    {
        fout.write((char*)&alphas[i],sizeof(double));
        fout.write((char*)&correct[i],sizeof(int));
        fout.write((char*)&wrong[i],sizeof(int));
        int size_of_type=weak_classifiers[i]->getType().size();
        fout.write((char*)&size_of_type,sizeof(int));
        char *wc_type=new char[size_of_type+1];
        sprintf(wc_type,"%s",weak_classifiers[i]->getType().c_str());
        fout.write((char*)wc_type,size_of_type*sizeof(char));
        delete [] wc_type;
        weak_classifiers[i]->toStream(fout);
    }
}
std::string StrongClassifier::toString () const [virtual], [inherited]
Encodes the classifier in a single string.
Returns
a string encoding the current classifier form
Implements iCub::boostMIL::WeakClassifier.
Definition at line 102 of file StrongClassifier.cpp.
References iCub::boostMIL::StrongClassifier::alphas, and iCub::boostMIL::StrongClassifier::weak_classifiers.
Referenced by iCub::boostMIL::StrongClassifier::saveAsString().
{
    std::stringstream strstr;
    for(unsigned int i = 0; i < this->weak_classifiers.size(); i++)
        strstr << "((alpha " << alphas[i] << ") (weak_classifier (" <<
      weak_classifiers[i]->toString() << "))) " << std::endl;
    return strstr.str().c_str();
}
void OnlineSupport::train (const std::list< Inputs * > & training_set) [virtual]
Trains the classifier with respect to a list of inputs.
Parameters
training_set the list of inputs over which train the classifier.
Implements iCub::boostMIL::StrongClassifier.
Definition at line 97 of file OnlineSupport.cpp.
References iCub::boostMIL::WeakClassifier::verbose.
{
    int cnt=0;
    for(std::list<Inputs*>::const_iterator itr = training_set.begin(); itr != training_set.end(); itr++)
    {
        train(*itr);
        if(verbose) fprintf(stdout,"[BoostMIL] trained sample n. %d\r",++cnt);
    }
}
void OnlineSupport::train (const Inputs * input, double weight = 1.0) [virtual]
Trains the classifier with respect to a single input.
Usually an online method.
Parameters
input the inputs over which train the classifier.
Implements iCub::boostMIL::StrongClassifier.
Definition at line 107 of file OnlineSupport.cpp.
References update().
{
    update(input,weight);
}
void OnlineSupport::update (const Inputs * input, double & weight) [virtual]
Updates the classifier with respect to an input with associated weight.
Usually an online method.
Parameters
input the input.
the relevance weight associated to the given input.
Implements iCub::boostMIL::StrongClassifier.
Definition at line 233 of file OnlineSupport.cpp.
References iCub::boostMIL::StrongClassifier::alphas, iCub::boostMIL::StrongClassifier::classify(), iCub::boostMIL::StrongClassifier::function_space, iCub::boostMIL::ClassifierFactory::instance(), isReady(), and iCub::boostMIL::StrongClassifier::weak_classifiers.
Referenced by train().
{
    //if the algorithm uses a function space, extract new weak learners from the input (if it is a positive
       sample).
    if(function_space.size()<max_function_space_size && input->getLabel() == +1)
    {
        ClassifierFactory::instance().pack(input,function_space);
        //avoid getting a function space too large
        while(function_space.size() > max_function_space_size)
        {
            delete function_space.front();
            function_space.pop_front();
        }
    }
    if(isReady())
    {
        //propagate the sample through the list of weak classifiers
        for(unsigned int i = 0; i < weak_classifiers.size(); i++)
        {
            weak_classifiers[i]->update(input,weight);
            if(weak_classifiers[i]->classify(input)>0)
            {
                if(input->getLabel()>0)
                {
                    correct[i]++;
                    double alpha = 1/(1+exp((double)-correct[i]+wrong[i]));
                    weight *= 1.0-alpha;
                }
                else
                {
                    wrong[i]++;
                    weight *= 1.0;
                }
            }
            else
            {
                if(input->getLabel()>0)
                    weight *= 1.1;
                else
                    weight *= 1.0;
            }
            alphas[i]=1/(1+exp((double)-correct[i]+wrong[i]));
            //if(weak_classifiers[i]->classify(input) > 0)
            //{
            // if(weak_classifiers[i]->cl]\assify(input) == input->getLabel())
            // {
            // weight *= 0.5/alphas[i];
            // }
            // else
            // {
            // weight *= 0.5/alphas[i]);
            // }
            //}
            
            //update alpha
            //alphas[i] = 0.5*log((1-weak_classifiers[i]->getError())/weak_classifiers[i]->getError());
        }
    }
}
The documentation for this class was generated from the following files:
C:/dev/icub-contrib-iit/boost-mil/lib/include/iCub/boostMIL/OnlineSupport.h
C:/dev/icub-contrib-iit/boost-mil/lib/src/OnlineSupport.cpp